name: "Unit and Integration"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: 'Branch or tag'
        required: true
        default: 'main'

jobs:
  test:
    name: "Unit"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - id: setup-go
        name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - id: install-dependencies
        name: install dependencies
        run: go mod download
      - id: test
        name: run tests
        run: |
          go test -json . 2>&1 | tee TestResults.json
          go test -json -bench . ./... -benchtime=10s 2>&1 | tee -a TestResults.json
      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.json
