name: "Unit and Integration"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: 'Branch or tag'
        required: true
        default: 'main'

jobs:
  test:
    name: "Unit"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - id: setup-go
        name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - id: install-dependencies
        name: install dependencies
        run: go mod download
#      - id: image-cache-setup
#        name: service container cache setup
#        uses: actions/cache@v3
#        with:
#          path: /tmp/image-cache
#          key: test-${{ runner.os }}-image-cache
#      - id: image-cache
#        name: service container cache
#        if: steps.image-cache-setup.outputs.cache-hit != 'true'
#        run: |
#          docker pull ${{ env.POSTGRESQL_IMAGE }}:${{ env.POSTGRESQL_VERSION }};
#
#          docker pull ${{ env.MYSQL_IMAGE }}:${{ env.MYSQL_VERSION }};
#
#          mkdir -p /tmp/image-cache;
#
#          docker save ${{ env.POSTGRESQL_IMAGE }}:${{ env.POSTGRESQL_VERSION }} > /tmp/image-cache/postgresql.tar;
#
#          docker save ${{ env.MYSQL_IMAGE }}:${{ env.MYSQL_VERSION }} > /tmp/image-cache/mysql.tar;
#      - id: image-cache-restore
#        name: service container cache restore
#        if: steps.image-cache-setup.outputs.cache-hit == 'true'
#        run: |
#          docker load -i /tmp/image-cache/postgresql.tar;
#
#          docker load -i /tmp/image-cache/mysql.tar;
      - id: test
        name: run tests
        run: |
          go test -json . 2>&1 | tee TestResults.json
          go test -json -bench . ./... -benchtime=10s 2>&1 | tee -a TestResults.json
      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.json
